Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2020-08, with the labels that each got.

#13 Add demo for 0.1.6 version
  demo/0.1.6/index.es.js
  demo/0.1.6/index.html
  demo/0.1.6/static/css/main.css
  demo/0.1.6/static/js/configureMxGraphGlobals.js
  demo/0.1.6/static/js/mxClient.min.js
  demo/index.html
Labels: enhancement

#14 feat(example): custom user task icon
  README.md
  examples/custom-user-task-icon/README.md
  examples/custom-user-task-icon/index.html
Labels: enhancement

#15 feat(example): custom colors
  README.md
  examples/custom-colors/README.md
  examples/custom-colors/index.html
  examples/index.html
Labels: enhancement

#16 feat(example): custom fonts
  README.md
  examples/custom-fonts/README.md
  examples/custom-fonts/index.html
  examples/index.html
Labels: enhancement

#17 feat(example): load remote bpmn diagrams
  README.md
  examples/index.html
  examples/load-remote-bpmn-diagrams/README.md
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement

#25 [DOC] insist that customization/extensions are currently hacks
  README.md
  examples/custom-colors/README.md
  examples/custom-fonts/README.md
  examples/custom-user-task-icon/README.md
Labels: documentation

#27 examples: add favicon
  examples/custom-colors/index.html
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/index.html
  examples/favicon.ico
  examples/index.html
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement

#30 Update the diagram for all activities with Call activity with markers
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#26 examples: bpmn diagrams in dedicated function
  examples/custom-colors/custom-colors.js
  examples/custom-fonts/custom-fonts.js
  examples/custom-user-task-icon/custom-user-task-icon.js
Labels: enhancement

#29 Examples: use unminified 0.1.7-preview
  demo/0.1.7-preview/index.es.js
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
  examples/custom-fonts/custom-fonts.js
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-user-task-icon/index.html
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement

#31 example: add custom colors depending on event type
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
Labels: enhancement

#32 Update BPMN activity test diagram
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#34 [FEAT] bpmn diagram with inner sub process
  bpmn-files/README.md
  bpmn-files/subprocesses.bpmn
  bpmn-files/subprocesses__bpmnio.svg
Labels: enhancement

#36 Add expanded call activity calling process, and call activity calling global task
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#33 chore(update): provide a script to update examples on new lib release
  scripts/update-lib-version.bash
Labels: enhancement

#37 [FEAT] integrate bpmn-visualization@0.1.7
  demo/0.1.7-preview/index.es.js
  demo/0.1.7/index.es.js
  demo/0.1.7/index.html
  demo/0.1.7/static/css/main.css
  demo/0.1.7/static/img/favicon.ico
  demo/0.1.7/static/js/configureMxGraphGlobals.js
  demo/0.1.7/static/js/mxClient.min.js
  demo/index.html
  examples/custom-colors/index.html
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/index.html
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement

#38 fix link to the 0.1.7 demo
  demo/index.html
Labels: bug

#40 update README files as examples are not using bpm-visualization@0.1.5
  examples/custom-colors/README.md
  examples/custom-fonts/README.md
  examples/custom-user-task-icon/README.md
  examples/load-remote-bpmn-diagrams/README.md
Labels: documentation

#41 Add various elements in the subprocess BPMN diagram
  bpmn-files/README.md
  bpmn-files/subprocesses.bpmn
  bpmn-files/subprocesses__bpmnio.svg
  bpmn-files/subprocesses_event_and_transaction.bpmn
  bpmn-files/subprocesses_event_and_transaction__bpmnio.svg
Labels: enhancement

#42 [DIAGRAM] Add initiating receive task
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#39 [DIAGRAM] add BPMN Artifacts diagram
  bpmn-files/README.md
  bpmn-files/artifacts_and_data_reference.bpmn
  bpmn-files/artifacts_and_data_reference__bpmnio.svg
  bpmn-files/text_annotations__bpmnio.bpmn
  bpmn-files/text_annotations__bpmnio.svg
Labels: enhancement

#43 [DIAGRAM] error start event in event subprocess
  bpmn-files/subprocesses_event_and_transaction.bpmn
  bpmn-files/subprocesses_event_and_transaction__bpmnio.svg
Labels: enhancement

#45 Open examples in a new tab
  examples/index.html
Labels: enhancement

#44 [DIAGRAM] add diagram to demonstrate pools
  bpmn-files/README.md
  bpmn-files/pools.bpmn
  bpmn-files/pools__bpmn-visualization-0.2.0-dev.png
Labels: enhancement

#46 [DIAGRAM] update activity diagram: 'instantiating receive task'
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#47 [DIAGRAM] activity diagram: add 'receive tasks' with various sizes
  bpmn-files/all_activity_types.bpmn
  bpmn-files/all_activity_types__bpmnio.svg
Labels: enhancement

#48 Examples: Integrate lib preview 0.2.0
  README.md
  demo/0.2.0/index.es.js
  demo/0.2.0/index.html
  demo/0.2.0/static/css/main.css
  demo/0.2.0/static/img/favicon.ico
  demo/0.2.0/static/js/configureMxGraphGlobals.js
  demo/0.2.0/static/js/demo.js
  demo/0.2.0/static/js/mxClient.min.js
  demo/index.html
  examples/custom-colors/README.md
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
  examples/custom-fonts/README.md
  examples/custom-fonts/custom-fonts.js
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/README.md
  examples/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-user-task-icon/index.html
  examples/load-remote-bpmn-diagrams/README.md
  examples/load-remote-bpmn-diagrams/index.html
  examples/utils.js
  scripts/update-lib-version.bash
Labels: enhancement

#50 [DIAGRAM] Enrich pool bpmn diagram example
  bpmn-files/pools.bpmn
  bpmn-files/pools__bpmn-visualization-0.2.0-dev.png
Labels: enhancement

#49 Examples: use improvements from bpmn-visualization@0.2.0
  demo/favicon.ico
  demo/index.html
  examples/index.html
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement
