Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2020-09, with the labels that each got.

#52 [DIAGRAM] Introduce Vertical & Horizontal Pools with Sub-Lane
  bpmn-files/pools.bpmn
  bpmn-files/pools__bpmn-visualization-0.2.0-dev.png
  bpmn-files/pools__bpmn-visualization-0.3.0-dev.png
Labels: enhancement

#55 [DOC] Add code of conduct badge in README
  README.md
Labels: infra:repo

#53 [FEAT] add design to the examples home page
  examples/custom-colors/index.html
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/index.html
  examples/index.html
  examples/load-remote-bpmn-diagrams/index.html
  examples/static/css/icons.min.css
  examples/static/css/main.css
  examples/static/css/spectre.min.css
  examples/static/img/logo_64x64.ico
  examples/static/img/preview_custom_colors.png
  examples/static/img/preview_custom_fonts.png
  examples/static/img/preview_custom_user_icon.png
  examples/static/img/preview_use_remote_diagram.png
Labels: enhancement

#56 [DOC] highlight demo and examples live environments
  README.md
Labels: documentation

#61 [FEAT] updated design for button and status in remote fetching example
  examples/load-remote-bpmn-diagrams/index.html
Labels: depends on another PR :warning:

#58 [DOC] Improve readme
  CONTRIBUTING.md
  README.md
  examples/custom-colors/README.md
  examples/custom-fonts/README.md
  examples/custom-user-task-icon/README.md
  examples/load-remote-bpmn-diagrams/README.md
  examples_home.png
Labels: documentation

#63 [FEAT] Add hacktoberfest example
  README.md
  examples/hacktoberfest-diagram/README.md
  examples/hacktoberfest-diagram/hacktoberfest-diagram.js
  examples/hacktoberfest-diagram/index.html
  examples/index.html
  examples/static/img/preview_hacktoberfest_diagram.png
Labels: enhancement

#62 [FEAT] add dropdown to select a specific remote diagram
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement
