Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2020-10, with the labels that each got.

#65 [FEAT] Add 0.4.0 demo and examples use lib 0.4.0
  demo/0.4.0/index.es.js
  demo/0.4.0/index.html
  demo/0.4.0/lib-integration.html
  demo/0.4.0/non-regression.html
  demo/0.4.0/static/css/main.css
  demo/0.4.0/static/img/favicon.ico
  demo/0.4.0/static/js/configureMxGraphGlobals.js
  demo/0.4.0/static/js/demo.js
  demo/0.4.0/static/js/lib-integration.js
  demo/0.4.0/static/js/mxClient.min.js
  demo/0.4.0/static/js/non-regression.js
  demo/index.html
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
  examples/custom-fonts/custom-fonts.js
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-user-task-icon/index.html
  examples/hacktoberfest-diagram/hacktoberfest-diagram.js
  examples/hacktoberfest-diagram/index.html
  examples/load-remote-bpmn-diagrams/index.html
  examples/utils.js
Labels: enhancement

#66 [FIX] Fix typo on Hacktoberfest example
  examples/hacktoberfest-diagram/hacktoberfest-diagram.js
Labels: bug

#69 [FEAT] Add examples using the browser npm package
  README.md
  examples/01-getting-started/README.md
  examples/01-getting-started/index.html
  examples/index.html
  examples/load-local-bpmn-diagrams/README.md
  examples/load-local-bpmn-diagrams/index.html
  examples/static/img/preview_01_getting_started.png
  examples/static/img/preview_use_local_diagram.png
  scripts/update-lib-version.bash
Labels: enhancement

#70 [FEAT] add navigation diagram example
  README.md
  examples/diagram-navigation/README.md
  examples/diagram-navigation/index.html
  examples/diagram-navigation/js/bpmn-visualization.js
  examples/index.html
  examples/static/img/preview_diagram_navigation.png
Labels: enhancement

#73 [INFRA] bump version - 0.5.0 for vanilla ts project
  examples/projects/typescript-vanilla-with-rollup/package.json
  scripts/update-lib-version.bash
Labels: infra:repo

#75 [FEAT] load remote bpmn - add C.7.0
  examples/load-remote-bpmn-diagrams/index.html
Labels: enhancement

#78 [INFRA] Add template for pull request
  .github/pull_request_template.md
Labels: infra:repo

#77 [FEAT] Example to demonstrate how to fit already loaded diagram
  README.md
  examples/diagram-fit-variants/README.md
  examples/diagram-fit-variants/index.html
  examples/index.html
  examples/static/img/preview_diagram_fit_variants.png
Labels: enhancement

#76 [FEAT] navigation example: allow diagram zoom and pan reset
  examples/diagram-navigation/README.md
  examples/diagram-navigation/index.html
Labels: enhancement

#82 Add 'fit on load' example
  README.md
  demo/0.5.1-alpha/bpmn-visualization.js
  examples/diagram-fit-on-load/README.md
  examples/diagram-fit-on-load/diagram-fit-on-load.js
  examples/diagram-fit-on-load/index.html
  examples/index.html
  examples/static/img/preview_diagram_fit-on-load.png
Labels: enhancement

#74 [REFACTOR] Replace 'paintUserIcon' to 'paintPersonIcon'
  demo/0.5.1-alpha/index.es.js
  demo/0.5.1-alpha/static/css/main.css
  demo/0.5.1-alpha/static/js/configureMxGraphGlobals.js
  demo/0.5.1-alpha/static/js/mxClient.min.js
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
  examples/custom-fonts/custom-fonts.js
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/README.md
  examples/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-user-task-icon/index.html
  examples/hacktoberfest-diagram/hacktoberfest-diagram.js
  examples/hacktoberfest-diagram/index.html
  examples/load-remote-bpmn-diagrams/index.html
  examples/utils.js
Labels: infra:build, infra:refactoring

#83 [FIX] Avoid extra top pixel translation when sticking the navbar
  examples/static/css/main.css
Labels: bug
