Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2020-11, with the labels that each got.

#84 [INFRA] Bump version 0.6.0
  demo/0.5.1-alpha/bpmn-visualization.js
  demo/0.5.1-alpha/index.es.js
  demo/0.6.0/index.es.js
  demo/0.6.0/index.html
  demo/0.6.0/lib-integration.html
  demo/0.6.0/navigation-diagram.html
  demo/0.6.0/non-regression.html
  demo/0.6.0/static/css/main.css
  demo/0.6.0/static/img/favicon.ico
  demo/0.6.0/static/js/configureMxGraphGlobals.js
  demo/0.6.0/static/js/demo.js
  demo/0.6.0/static/js/lib-integration.js
  demo/0.6.0/static/js/mxClient.min.js
  demo/0.6.0/static/js/navigation-diagram.js
  demo/0.6.0/static/js/non-regression.js
  demo/index.html
  examples/01-getting-started/README.md
  examples/01-getting-started/index.html
  examples/custom-colors/custom-colors.js
  examples/custom-colors/index.html
  examples/custom-fonts/custom-fonts.js
  examples/custom-fonts/index.html
  examples/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-user-task-icon/index.html
  examples/diagram-fit-on-load/index.html
  examples/diagram-fit-variants/index.html
  examples/diagram-navigation/index.html
  examples/hacktoberfest-diagram/hacktoberfest-diagram.js
  examples/hacktoberfest-diagram/index.html
  examples/load-local-bpmn-diagrams/index.html
  examples/load-remote-bpmn-diagrams/index.html
  examples/projects/typescript-vanilla-with-rollup/package-lock.json
  examples/projects/typescript-vanilla-with-rollup/package.json
  examples/utils.js
Labels: enhancement

#90 [FEAT] Add more `event-based gateways` in the bpmn diagram
  bpmn-files/all_gateway_types.bpmn
  bpmn-files/all_gateway_types__bpmn.io.svg
Labels: enhancement

#94 [REFACTOR] Update the example for fit after load
  demo/0.7.0/bpmn-visualization.js
  examples/diagram-fit-variants/index.html
  examples/diagram-navigation/index.html
Labels: infra:refactoring

#97 [BUG] Fix the script to update the library version for MacOs
  scripts/update-lib-version.bash
Labels: bug

#99 [REFACTOR] Update the FitType API
  examples/diagram-fit-on-load/README.md
  examples/diagram-fit-on-load/diagram-fit-on-load.js
  examples/diagram-fit-on-load/index.html
  examples/diagram-fit-variants/README.md
  examples/diagram-fit-variants/index.html
  tmp/bpmn-visualization.js
Labels: infra:refactoring

#101 [DOC] update links to bpmn-visualization documentation
  README.md
  examples/custom-colors/README.md
  examples/custom-fonts/README.md
  examples/custom-user-task-icon/README.md
  examples/hacktoberfest-diagram/README.md
Labels: depends on another PR :warning:

#103 [EXAMPLE] Add example to open a modal on mouse over on a modal
  README.md
  examples/index.html
  examples/interaction/call_activity_with_modal_on_mouse_over/README.md
  examples/interaction/call_activity_with_modal_on_mouse_over/index.html
  examples/interaction/call_activity_with_modal_on_mouse_over/index.js
  examples/interaction/call_activity_with_modal_on_mouse_over/modal.js
  examples/static/img/preview/interaction/preview_call_activity_with_modal_on_mouse_over.png
  tmp/bpmn-visualization.js
Labels: enhancement
