Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2020-12, with the labels that each got.

#107 [EXAMPLE] Add example to open a tab on click on a call activity
  README.md
  examples/index.html
  examples/interaction/call-activity-with-modal-on-mouse-over/README.md
  examples/interaction/call-activity-with-modal-on-mouse-over/index.html
  examples/interaction/call-activity-with-modal-on-mouse-over/index.js
  examples/interaction/call-activity-with-modal-on-mouse-over/modal.js
  examples/interaction/call-activity-with-tabs-on-click/README.md
  examples/interaction/call-activity-with-tabs-on-click/index.html
  examples/interaction/call-activity-with-tabs-on-click/index.js
  examples/static/img/preview/interaction/call_activity_with_modal_on_mouse_over.png
  examples/static/img/preview/interaction/call_activity_with_tabs_on_click.png
Labels: enhancement

#108 [EXAMPLE] Add example to load another BPMN diagram in the same container on double click on a call activity
  README.md
  examples/index.html
  examples/interaction/call-activity-with-reload-on-dblclick/README.md
  examples/interaction/call-activity-with-reload-on-dblclick/breadcrumbs.js
  examples/interaction/call-activity-with-reload-on-dblclick/index.html
  examples/interaction/call-activity-with-reload-on-dblclick/index.js
  examples/static/img/preview/interaction/call_activity_with_reload_on_dblclick.png
Labels: enhancement

#111 [REFACTOR] Extract BPMN Diagrams out of examples
  examples/bpmn-diagrams.js
  examples/custom-bpmn-theme/custom-colors/custom-colors.js
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-fonts/custom-fonts.js
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-user-task-icon/custom-user-task-icon.js
  examples/custom-bpmn-theme/custom-user-task-icon/index.html
  examples/custom-bpmn-theme/hacktoberfest-diagram/hacktoberfest-diagram.js
  examples/custom-bpmn-theme/hacktoberfest-diagram/index.html
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/README.md
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.js
  examples/custom-navigation/call-activity-with-reload-on-dblclick/README.md
  examples/custom-navigation/call-activity-with-reload-on-dblclick/index.html
  examples/custom-navigation/call-activity-with-reload-on-dblclick/index.js
  examples/custom-navigation/call-activity-with-tabs-on-click/README.md
  examples/custom-navigation/call-activity-with-tabs-on-click/index.html
  examples/custom-navigation/call-activity-with-tabs-on-click/index.js
  examples/diagram-navigation/diagram-fit-after-load/index.html
  examples/diagram-navigation/diagram-fit-on-load/diagram-fit-on-load.js
  examples/diagram-navigation/diagram-fit-on-load/index.html
  examples/diagram-navigation/diagram-navigation/index.html
  examples/display-bpmn-diagram/01-getting-started/index.html
  examples/index.html
Labels: infra:refactoring

#112 [EXAMPLE] Add custom running dashed animation on a Message Flow
  README.md
  examples/bpmn-diagrams.js
  examples/custom-animation/running-dashed-message-flow/README.md
  examples/custom-animation/running-dashed-message-flow/index.html
  examples/custom-animation/running-dashed-message-flow/index.js
  examples/index.html
  examples/static/img/preview/custom-animation/running_dashed_message_flow.gif
Labels: enhancement

#105 [EXAMPLE] Popover - static
  README.md
  examples/custom-interaction/popover-static/README.md
  examples/custom-interaction/popover-static/index.html
  examples/custom-interaction/popover-static/index.js
  examples/index.html
  examples/static/img/preview/custom-interaction/popover.png
  examples/static/js/dom-helper.js
Labels: enhancement

#116 [BUG] back to top fix for safari
  examples/index.html
Labels: bug

#118 [INFRA] use bpmn-visualization@0.9.0
  demo/index.es.js
  demo/navigation-diagram.html
  demo/static/css/main.css
  demo/static/js/navigation-diagram.js
  examples/custom-animation/growing-sequence-flow/README.md
  examples/custom-animation/growing-sequence-flow/index.html
  examples/custom-animation/growing-sequence-flow/index.js
  examples/custom-animation/running-dashed-message-flow/README.md
  examples/custom-animation/running-dashed-message-flow/index.html
  examples/custom-animation/running-dashed-message-flow/index.js
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-user-task-icon/index.html
  examples/custom-bpmn-theme/hacktoberfest-diagram/index.html
  examples/custom-interaction/apply-css-classes/README.md
  examples/custom-interaction/apply-css-classes/index.html
  examples/custom-interaction/popover-static/index.html
  examples/custom-interaction/popover-static/index.js
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/README.md
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.js
  examples/custom-navigation/call-activity-with-reload-on-dblclick/README.md
  examples/custom-navigation/call-activity-with-reload-on-dblclick/index.html
  examples/custom-navigation/call-activity-with-reload-on-dblclick/index.js
  examples/custom-navigation/call-activity-with-tabs-on-click/README.md
  examples/custom-navigation/call-activity-with-tabs-on-click/index.html
  examples/custom-navigation/call-activity-with-tabs-on-click/index.js
  examples/diagram-navigation/diagram-fit-after-load/index.html
  examples/diagram-navigation/diagram-fit-on-load/index.html
  examples/diagram-navigation/diagram-navigation/index.html
  examples/display-bpmn-diagram/01-getting-started/README.md
  examples/display-bpmn-diagram/01-getting-started/index.html
  examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
  examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
  examples/misc/compare-with-bpmn-js/index.html
  examples/projects/typescript-vanilla-with-rollup/package-lock.json
  examples/projects/typescript-vanilla-with-rollup/package.json
  scripts/update-lib-version.bash
Labels: enhancement
