Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2021-05, with the labels that each got.

#165 [DOC] Replace 'Custom interaction' by 'Custom behavior'
  README.md
  examples/custom-behavior/apply-css-classes/README.md
  examples/custom-behavior/apply-css-classes/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/README.md
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/index.js
  examples/custom-behavior/popover-static/README.md
  examples/custom-behavior/popover-static/index.html
  examples/custom-behavior/popover-static/index.js
  examples/custom-behavior/select-elements-by-bpmn-kind/README.md
  examples/custom-behavior/select-elements-by-bpmn-kind/index.html
  examples/index.html
  examples/projects/typescript-vanilla-with-rollup/package-lock.json
  examples/static/img/preview/custom-behavior/apply-css-classes.png
  examples/static/img/preview/custom-behavior/javascript-tooltip-and-popover.png
  examples/static/img/preview/custom-behavior/popover.png
  examples/static/img/preview/custom-behavior/select-elements-by-bpmn-kind.png
Labels: documentation, infra:refactoring

#167 [DOC] Replace 'Custom navigation' by 'Custom behavior'
  README.md
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/README.md
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.js
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/modal.js
  examples/custom-behavior/call-activity-with-reload-on-dblclick/README.md
  examples/custom-behavior/call-activity-with-reload-on-dblclick/breadcrumbs.js
  examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
  examples/custom-behavior/call-activity-with-reload-on-dblclick/index.js
  examples/custom-behavior/call-activity-with-tabs-on-click/README.md
  examples/custom-behavior/call-activity-with-tabs-on-click/index.html
  examples/custom-behavior/call-activity-with-tabs-on-click/index.js
  examples/index.html
  examples/static/img/preview/custom-behavior/call_activity_with_modal_on_mouse_over.png
  examples/static/img/preview/custom-behavior/call_activity_with_reload_on_dblclick.png
  examples/static/img/preview/custom-behavior/call_activity_with_tabs_on_click.png
Labels: documentation

#173 [FEAT] Simplify the 'diagram navigation' example
  examples/diagram-navigation/diagram-navigation/index.html
  examples/diagram-navigation/diagram-navigation/index.js
Labels: enhancement

#174 [REFACTOR] Move the 'Load and Navigation demo' to another folder to have several demos
  .github/workflows/update_bpmn_visualization_version.yml
  README.md
  demo/load-and-navigation/elements-identification.html
  demo/load-and-navigation/index.es.js
  demo/load-and-navigation/index.html
  demo/load-and-navigation/lib-integration.html
  demo/load-and-navigation/non-regression.html
  demo/load-and-navigation/overlays.html
  demo/load-and-navigation/rendering-diagram.html
  demo/load-and-navigation/static/css/styles.css
  demo/load-and-navigation/static/css/tailwind.css
  demo/load-and-navigation/static/css/test.css
  demo/load-and-navigation/static/img/favicon.ico
  demo/load-and-navigation/static/img/logo_64x64.ico
  demo/load-and-navigation/static/js/demo.js
  demo/load-and-navigation/static/js/elements-identification.js
  demo/load-and-navigation/static/js/lib-integration.js
  demo/load-and-navigation/static/js/non-regression.js
  demo/load-and-navigation/static/js/overlays.js
  demo/load-and-navigation/static/js/rendering-diagram.js
  demo/load-and-navigation/static/js/test.js
  examples/index.html
  examples/static/img/preview/demo/load_and_navigation.png
Labels: infra:refactoring

#170 [EXAMPLE] Add new example to customize the default style for the overlays
  README.md
  examples/custom-bpmn-theme/custom-colors/README.md
  examples/custom-bpmn-theme/custom-fonts/README.md
  examples/custom-bpmn-theme/custom-user-task-icon/README.md
  examples/custom-bpmn-theme/hacktoberfest-diagram/README.md
  examples/index.html
  examples/overlays/custom-overlay-default-style/README.md
  examples/overlays/custom-overlay-default-style/index.html
  examples/overlays/custom-overlay-default-style/index.js
  examples/static/img/preview/overlays/custom-overlay-default-style.png
Labels: enhancement

#178 [INFRA] Bump 3rd party libs in the popup/popover custom behavior example
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/index.js
Labels: dependencies

#179 [FEAT] Add new demo for process frequency & timing monitoring
  demo/monitoring-all-process-instances/README.md
  demo/monitoring-all-process-instances/execution-data.js
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/index.js
  demo/monitoring-all-process-instances/switch.css
  examples/index.html
  examples/static/img/preview/demo/monitoring-all-process-instances.png
  examples/static/js/bpmn-diagrams.js
Labels: enhancement

#184 [FEAT] Improve the 'monitoring' demo
  demo/monitoring-all-process-instances/execution-data.js
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/index.js
Labels: enhancement

#183 [FEAT] update usage in the diagram navigation page
  examples/diagram-navigation/diagram-navigation/index.html
Labels: enhancement

#185 [INFRA] Fix script to update the lib version in the demos
  scripts/update-lib-version.bash
Labels: infra:build

#189 [FEAT] Improve the 'highlight path' example
  examples/custom-behavior/apply-css-classes/index.html
Labels: enhancement

#190 [FEAT] Bump bpmn-js from 8.3.1 to 8.6.0 used in the comparison examples
  examples/misc/compare-with-bpmn-js/index.html
Labels: enhancement
