Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2021-09, with the labels that each got.

#224 [FIX] Use new logo for favicon in project examples
  examples/projects/javascript-vanilla-with-webpack/favicon.ico
  examples/projects/javascript-vanilla-with-webpack/favicon.png
  examples/projects/javascript-vanilla-with-webpack/index.html
  examples/projects/typescript-vanilla-with-rollup/src/static/img/favicon.ico
  examples/projects/typescript-vanilla-with-rollup/src/static/img/favicon.png
Labels: bug

#223 [FEAT] Add an example running in CodeSandbox
  README.md
  examples/index.html
  examples/static/img/preview/misc/codesandbox.png
Labels: enhancement

#226 [FEAT] Monitoring demo : Update the design of the panel for the legends & diagram
  demo/monitoring-all-process-instances/index.html
Labels: enhancement

#221 [FEAT] Demo time/frequency monitoring: enable/disable overlays and paths
  demo/monitoring-all-process-instances/css/legend.css
  demo/monitoring-all-process-instances/css/path.css
  demo/monitoring-all-process-instances/css/switch.css
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/index.js
  demo/monitoring-all-process-instances/js/frequency-execution-data.js
  demo/monitoring-all-process-instances/js/index.js
  demo/monitoring-all-process-instances/js/time-execution-data.js
  demo/monitoring-all-process-instances/switch.css
Labels: enhancement

#227 [FEAT] Demo time/frequency monitoring: Improve button style
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/index.js
Labels: enhancement

#235 [FEAT] Update JavaScript and TypeScript projects
  examples/projects/javascript-vanilla-with-webpack/package-lock.json
  examples/projects/javascript-vanilla-with-webpack/package.json
  examples/projects/typescript-vanilla-with-rollup/.eslintrc.js
  examples/projects/typescript-vanilla-with-rollup/README.md
  examples/projects/typescript-vanilla-with-rollup/package-lock.json
  examples/projects/typescript-vanilla-with-rollup/package.json
  examples/projects/typescript-vanilla-with-rollup/rollup.config.js
Labels: enhancement

#229 [REFACTOR] Demo time/frequency monitoring: Introduce Legend class
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/frequency-execution-data.js
  demo/monitoring-all-process-instances/js/index.js
  demo/monitoring-all-process-instances/js/legend.js
  demo/monitoring-all-process-instances/js/time-execution-data.js
Labels: infra:refactoring

#231 [REFACTOR] Demo time/frequency monitoring: Introduce UseCase classes
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/index.js
  demo/monitoring-all-process-instances/js/use-case.js
Labels: infra:refactoring

#232 [REFACTOR] Demo time/frequency monitoring: Introduce state for buttons
  demo/monitoring-all-process-instances/js/index.js
Labels: infra:refactoring

#233 [FEAT] Demo time/frequency monitoring: Add legend titles
  demo/monitoring-all-process-instances/css/legend.css
  demo/monitoring-all-process-instances/index.html
Labels: enhancement

#234 [FEAT] Monitoring demo: Hide the legends when it's not necessary
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/execution-data/execution-data.js
  demo/monitoring-all-process-instances/js/legend.js
  demo/monitoring-all-process-instances/js/use-case.js
Labels: enhancement

#236 [FEAT] Monitoring demo: Change legend colors for time data
  demo/monitoring-all-process-instances/js/execution-data/time-execution-data.js
Labels: enhancement

#237 [REFACTOR] Move diagrams in a dedicated folder
  demo/monitoring-all-process-instances/index.html
  examples/custom-behavior/apply-css-classes/index.html
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
  examples/custom-behavior/call-activity-with-tabs-on-click/index.html
  examples/custom-behavior/growing-sequence-flow/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/popover-static/index.html
  examples/custom-behavior/running-dashed-message-flow/index.html
  examples/custom-behavior/select-elements-by-bpmn-kind/index.html
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-user-task-icon/index.html
  examples/custom-bpmn-theme/hacktoberfest-diagram/index.html
  examples/diagram-navigation/diagram-fit-after-load/index.html
  examples/diagram-navigation/diagram-fit-on-load/index.html
  examples/diagram-navigation/diagram-navigation/index.html
  examples/display-bpmn-diagram/01-getting-started/index.html
  examples/overlays/add-remove/index.html
  examples/overlays/add-stylized/index.html
  examples/overlays/custom-overlay-default-style/index.html
  examples/static/js/diagram/bpmn-diagram-miwg-test-suite-a_4_1.js
  examples/static/js/diagram/bpmn-diagram-miwg-test-suite-c_1_0.js
  examples/static/js/diagram/bpmn-diagram-miwg-test-suite-c_1_1.js
  examples/static/js/diagram/bpmn-diagram-miwg-test-suite-c_2_0.js
  examples/static/js/diagram/bpmn-diagrams.js
Labels: infra:refactoring

#240 [REFACTOR] Move the Hacktoberfest example to the Demo folder
  README.md
  demo/hacktoberfest-custom-themes/README.md
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/index.js
  examples/index.html
  examples/static/img/preview/demo/hacktoberfest-custom-themes.png
Labels: infra:refactoring

#239 [REFACTOR] Apply same style in the Hacktoberfest example as in the Monitoring demo
  demo/hacktoberfest-custom-themes/README.md
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/index.js
  demo/hacktoberfest-custom-themes/js/dark-use-case.js
  demo/hacktoberfest-custom-themes/js/hacktoberfest-use-case.js
  demo/hacktoberfest-custom-themes/js/index.js
  demo/hacktoberfest-custom-themes/js/light-use-case.js
  demo/hacktoberfest-custom-themes/js/theme.js
  demo/static/css/controls.css
  demo/static/js/use-case.js
Labels: infra:refactoring

#241 [FEAT] Hacktoberfest demo: Add 2021 theme
  README.md
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/js/index.js
  demo/hacktoberfest-custom-themes/js/theme.js
  examples/static/img/preview/demo/hacktoberfest-custom-themes.png
  examples_home_for_hacktoberfest.png
Labels: enhancement

#243 [REFACTOR] Remove usage of mxgraph.mxConstants in examples
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/js/theme-bpmn-visualization.js
  examples/custom-bpmn-theme/custom-colors/README.md
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-colors/index.js
  examples/custom-bpmn-theme/custom-fonts/README.md
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-fonts/index.js
  examples/static/js/style-identifiers.js
Labels: infra:refactoring

#244 [DOC] Improve 'how to run locally' in README
  README.md
Labels: documentation
