Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2021-06, with the labels that each got.

#197 [FIX] Fix overlay fill color in the Frequency monitoring demo
  demo/monitoring-all-process-instances/execution-data.js
Labels: bug

#198 [FEAT] Customize paths on the demo monitoring
  demo/monitoring-all-process-instances/execution-data.js
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/index.js
  examples/static/js/bpmn-diagrams.js
Labels: enhancement

#199 [INFRA] Remove Marcin from the auto reviewers
  .github/workflows/update_bpmn_visualization_version.yml
Labels: infra:build

#200 [REFACTOR] Simplify custom user task icon code
  examples/custom-bpmn-theme/custom-user-task-icon/custom-user-task-icon.js
Labels: infra:refactoring
