Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2022-10, with the labels that each got.

#405 [FEAT] Simplify integration of bpmn-visualization in TS projects
  .github/workflows/check-typescript-projects.yml
  README.md
  projects/typescript-vanilla-with-parcel/src/index.ts
  projects/typescript-vanilla-with-parcel/src/mxgraph-initializer.ts
  projects/typescript-vanilla-with-parcel/tsconfig.json
  projects/typescript-vanilla-with-rollup/tsconfig.json
  projects/typescript-vanilla-with-vitejs/src/main.ts
  projects/typescript-vanilla-with-vitejs/src/mxgraph-initializer.ts
  projects/typescript-vanilla-with-vitejs/tsconfig.json
Labels: enhancement

#407 [FEAT] Update the preview image for the Hacktoberfest demo
  README.md
  examples/static/img/preview/demo/hacktoberfest-custom-themes.png
  examples_home_for_hacktoberfest.png
Labels: enhancement

#412 [FEAT] Add the tutorial `getting started`
  README.md
  examples/index.html
  examples/static/img/preview/tutorials/getting-started.gif
  examples/static/img/preview/tutorials/quick-start.png
  examples/static/js/link-to-sources.js
  tutorials/getting-started/README.md
  tutorials/getting-started/index.html
  tutorials/quick-start/README.md
  tutorials/quick-start/index.html
  tutorials/quick-start/index.js
Labels: enhancement

#413 [DOC] Improve the README title in existing projects
  projects/javascript-vanilla-with-webpack/README.md
  projects/typescript-vanilla-with-parcel/README.md
  projects/typescript-vanilla-with-rollup/README.md
  projects/typescript-vanilla-with-vitejs/README.md
Labels: documentation

#414 [BUG] Remove unnecessary scripts from `html` page of `getting-started` tutorial
  tutorials/getting-started/index.html
Labels: bug

#420 [REFACTOR] Use SVG favicon instead of PNG
  demo/hacktoberfest-custom-themes/index.html
  demo/icpm-2022/index.html
  demo/monitoring-all-process-instances/index.html
  demo/predictions/index.html
  examples/custom-behavior/apply-css-classes/index.html
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
  examples/custom-behavior/call-activity-with-tabs-on-click/index.html
  examples/custom-behavior/growing-sequence-flow/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/running-dashed-message-flow/index.html
  examples/custom-behavior/select-elements-by-bpmn-kind/index.html
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-edge-marker-colors/index.html
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-user-task-icon/index.html
  examples/diagram-navigation/diagram-fit-after-load/index.html
  examples/diagram-navigation/diagram-fit-on-load/index.html
  examples/diagram-navigation/diagram-navigation/index.html
  examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
  examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
  examples/display-bpmn-diagram/pools-filter-on-load/index.html
  examples/favicon.png
  examples/favicon.svg
  examples/index.html
  examples/misc/compare-with-bpmn-js/index.html
  examples/misc/compare-with-kie-editors-standalone/index.html
  examples/overlays/add-remove/index.html
  examples/overlays/add-stylized/index.html
  examples/overlays/custom-overlay-default-style/index.html
  projects/javascript-vanilla-with-webpack/favicon.png
  projects/javascript-vanilla-with-webpack/favicon.svg
  projects/javascript-vanilla-with-webpack/index.html
  projects/typescript-vanilla-with-rollup/src/index.html
  projects/typescript-vanilla-with-rollup/src/static/img/favicon.png
  projects/typescript-vanilla-with-rollup/src/static/img/favicon.svg
  tutorials/getting-started/index.html
  tutorials/quick-start/index.html
Labels: hacktoberfest-accepted

#421 [FIX] Update the page title of the ICPM 2022 Demo
  demo/icpm-2022/index.html
Labels: bug
