Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2022-11, with the labels that each got.

#422 [DOC] Revert Hacktoberfest hero image from the README
  README.md
Labels: documentation

#411 [FEAT] Add an example of a project using Angular
  .github/workflows/check-typescript-projects.yml
  README.md
  projects/typescript-angular/.browserslistrc
  projects/typescript-angular/.editorconfig
  projects/typescript-angular/.gitignore
  projects/typescript-angular/.npmrc
  projects/typescript-angular/.vscode/extensions.json
  projects/typescript-angular/.vscode/launch.json
  projects/typescript-angular/.vscode/tasks.json
  projects/typescript-angular/README.md
  projects/typescript-angular/angular.json
  projects/typescript-angular/karma.conf.js
  projects/typescript-angular/package.json
  projects/typescript-angular/src/app/app.component.css
  projects/typescript-angular/src/app/app.component.html
  projects/typescript-angular/src/app/app.component.spec.ts
  projects/typescript-angular/src/app/app.component.ts
  projects/typescript-angular/src/app/app.module.ts
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.css
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.html
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.spec.ts
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.ts
  projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.css
  projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.html
  projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.spec.ts
  projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.ts
  projects/typescript-angular/src/app/services/bpmn-diagram.service.spec.ts
  projects/typescript-angular/src/app/services/bpmn-diagram.service.ts
  projects/typescript-angular/src/assets/.gitkeep
  projects/typescript-angular/src/environments/environment.prod.ts
  projects/typescript-angular/src/environments/environment.ts
  projects/typescript-angular/src/favicon.svg
  projects/typescript-angular/src/index.html
  projects/typescript-angular/src/main.ts
  projects/typescript-angular/src/polyfills.ts
  projects/typescript-angular/src/styles.css
  projects/typescript-angular/src/test.ts
  projects/typescript-angular/tsconfig.app.json
  projects/typescript-angular/tsconfig.json
  projects/typescript-angular/tsconfig.spec.json
Labels: enhancement, hacktoberfest-accepted

#424 [FEAT] Angular example: add zoom reset and notifications
  projects/typescript-angular/package.json
  projects/typescript-angular/src/app/app.module.ts
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.css
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.html
  projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.ts
  projects/typescript-angular/src/app/bpmn-examples/notification-zone.component.ts
  projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.ts
  projects/typescript-angular/src/app/services/actions-notifier.service.spec.ts
  projects/typescript-angular/src/app/services/actions-notifier.service.ts
  projects/typescript-angular/src/app/services/bpmn-diagram.service.ts
  projects/typescript-angular/src/app/services/bpmn-navigation.service.spec.ts
  projects/typescript-angular/src/app/services/bpmn-navigation.service.ts
  projects/typescript-angular/src/app/utils/types.ts
  projects/typescript-angular/src/styles.css
Labels: enhancement

#426 [INFRA] Update parcel from 2.7.0 to 2.8.0
  projects/typescript-vanilla-with-parcel/package.json
Labels: chore

#427 [FIX] Avoid build errors on new parcel releases
  projects/typescript-vanilla-with-parcel/package.json
Labels: bug
