Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2023-07, with the labels that each got.

#518 chore: rework the config of the lit project
  projects/typescript-lit-element/patches/mxgraph+4.2.2.patch
  projects/typescript-lit-element/tsconfig.json
Labels: chore

#515 refactor: use the new flow/flownode links from the bpmn semantic in the predictions demo
  demo/predictions/index.html
  demo/predictions/js/data.js
  demo/predictions/js/path.js
  demo/predictions/js/prediction-use-case.js
Labels: refactoring

#519 refactor(theme): use global style instead of StyleDefault
  examples/custom-bpmn-theme/custom-colors/README.md
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-colors/index.js
  examples/custom-bpmn-theme/custom-fonts/README.md
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-fonts/index.js
Labels: refactoring

#520 fix(prediction): fix the computing of the paths in the Prediction demo
  demo/predictions/js/data.js
  demo/predictions/js/path.js
Labels: bug

#522 feat(prediction): make non predicted path less visible
  demo/predictions/css/demo.css
  demo/predictions/js/data.js
  demo/predictions/js/path.js
  demo/predictions/js/prediction-use-case.js
  demo/predictions/js/style.js
Labels: enhancement

#523 feat(prediction): review css to use `rem` instead of `em` or `px`
  demo/predictions/css/demo.css
Labels: enhancement

#524 feat(prediction): restore message flow icons in the BPMN diagram
  demo/predictions/css/demo.css
  examples/static/js/diagram/bpmn-diagram-bpmn-spec-pizza.js
Labels: enhancement

#527 feat(prediction): deactivate the navigation
  demo/predictions/css/demo.css
  demo/predictions/css/legend.css
  demo/predictions/index.html
  demo/predictions/js/prediction-use-case.js
  demo/predictions/js/style.js
Labels: enhancement

#529 feat(prediction): display the demo in the html home page for a public access
  README.md
  demo/prediction/README.md
  demo/prediction/css/demo.css
  demo/prediction/css/legend.css
  demo/prediction/index.html
  demo/prediction/js/data.js
  demo/prediction/js/index.js
  demo/prediction/js/path.js
  demo/prediction/js/prediction-use-case.js
  demo/prediction/js/style.js
  examples/index.html
  examples/static/img/preview/demo/prediction.png
  examples/static/js/diagram/bpmn-diagram-bpmn-spec-pizza.js
Labels: enhancement

#528 feat(prediction): add popup popover
  demo/prediction/css/demo.css
  demo/prediction/index.html
  demo/prediction/js/data.js
  demo/prediction/js/prediction-use-case.js
  demo/prediction/js/style.js
  demo/static/js/use-case.js
Labels: enhancement

#531 refactor(vue-demo): use `bv-experimental-add-ons`
  projects/typescript-vue/package.json
  projects/typescript-vue/src/app.vue
  projects/typescript-vue/src/bpmn-utils.ts
Labels: refactoring
