Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2023-10, with the labels that each got.

#559 refactor(demo): use a single bpmn container in the monitoring demo
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/index.js
  demo/monitoring-all-process-instances/js/monitoring-use-case.js
Labels: refactoring

#572 chore: bump dev dependencies in projects
  projects/javascript-vanilla-with-webpack/package.json
  projects/typescript-angular/package.json
  projects/typescript-lit-element/.npmrc
  projects/typescript-lit-element/package-lock.json
  projects/typescript-lit-element/package.json
  projects/typescript-vanilla-with-rollup/package.json
  projects/typescript-vanilla-with-vitejs/package.json
  projects/typescript-vue/package.json
Labels: chore

#574 chore(dev-deps): bump parcel from 2.9.3 to 2.10.0
  projects/typescript-vanilla-with-parcel/package.json
Labels: chore, dependencies, javascript

#575 fix(BpmnSemantic): do not display properties with undefined values
  examples/custom-behavior/javascript-tooltip-and-popover/index.js
Labels: bug

#564 refactor(demo): simplify the UseCase classes and how to set theme
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/js/index.js
  demo/hacktoberfest-custom-themes/js/theme-bpmn-visualization.js
  demo/hacktoberfest-custom-themes/js/use-case/hacktoberfest-use-case.js
  demo/hacktoberfest-custom-themes/js/use-case/theme-use-case.js
  demo/monitoring-all-process-instances/index.html
  demo/monitoring-all-process-instances/js/index.js
  demo/monitoring-all-process-instances/js/monitoring-use-case.js
  demo/prediction/index.html
  demo/prediction/js/index.js
  demo/prediction/js/prediction-use-case.js
  demo/static/js/use-case.js
Labels: refactoring
