Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2023-09, with the labels that each got.

#536 feat(demo): reference the demo of bv-experimental-add-ons
  README.md
  examples/index.html
  examples/static/img/preview/demo/bv-experimental-add-ons.png
Labels: enhancement

#541 feat: use resource integrity when loading bpmn-visualization from CDN
  .github/workflows/update_bpmn_visualization_version.yml
  demo/draw-path/index.html
  demo/hacktoberfest-custom-themes/index.html
  demo/monitoring-all-process-instances/index.html
  demo/prediction/index.html
  examples/custom-behavior/apply-css-classes/index.html
  examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
  examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
  examples/custom-behavior/call-activity-with-tabs-on-click/index.html
  examples/custom-behavior/growing-sequence-flow/index.html
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/running-dashed-message-flow/index.html
  examples/custom-behavior/select-elements-by-bpmn-kind/index.html
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-edge-marker-colors/index.html
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-user-task-icon/index.html
  examples/diagram-navigation/diagram-fit-after-load/index.html
  examples/diagram-navigation/diagram-fit-on-load/index.html
  examples/diagram-navigation/diagram-navigation/index.html
  examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
  examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
  examples/display-bpmn-diagram/pools-filter-on-load/index.html
  examples/misc/compare-with-bpmn-js/index.html
  examples/misc/compare-with-kie-editors-standalone/index.html
  examples/overlays/add-remove/index.html
  examples/overlays/add-stylized/index.html
  examples/overlays/custom-overlay-default-style/index.html
  scripts/update-lib-version.bash
Labels: enhancement

#544 feat: check integrity of all external JS loaded from CDN
  demo/draw-path/index.html
  demo/monitoring-all-process-instances/index.html
Labels: enhancement

#547 chore: bump version of competitors in examples
  examples/misc/compare-with-bpmn-js/index.html
  examples/misc/compare-with-kie-editors-standalone/index.html
Labels: enhancement

#554 feat(hacktoberfest): add 2023 theme
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/js/theme.js
Labels: enhancement

#555 feat: improve the layout of the Hacktoberfest diagram
  examples/static/img/preview/demo/hacktoberfest-custom-themes.png
  examples/static/js/diagram/bpmn-diagrams.js
Labels: enhancement

#557 refactor(demo): use a single bpmn container in the hacktoberfest demo
  demo/hacktoberfest-custom-themes/index.html
  demo/hacktoberfest-custom-themes/js/index.js
  demo/hacktoberfest-custom-themes/js/theme.js
  demo/hacktoberfest-custom-themes/js/use-case/hacktoberfest-use-case.js
  demo/hacktoberfest-custom-themes/js/use-case/theme-use-case.js
Labels: refactoring

#553 chore: update 3rd party libs used in examples
  examples/custom-behavior/javascript-tooltip-and-popover/index.html
  examples/custom-behavior/select-elements-by-bpmn-kind/index.html
Labels: chore

#561 feat: simplify the description in the Hacktoberfest demo
  demo/hacktoberfest-custom-themes/index.html
Labels: enhancement

#558 refactor(demo): have a single bpmn container in the prediction demo
  demo/prediction/index.html
  demo/prediction/js/index.js
  demo/prediction/js/prediction-use-case.js
Labels: refactoring
