Repository process-analytics/bpmn-visualization-examples, pull requests merged in 2023-06, with the labels that each got.

#501 feat: add a "Vue" integration project
  .github/workflows/check-projects.yml
  README.md
  projects/typescript-vue/.gitignore
  projects/typescript-vue/.npmrc
  projects/typescript-vue/README.md
  projects/typescript-vue/docs/home.png
  projects/typescript-vue/favicon.svg
  projects/typescript-vue/index.html
  projects/typescript-vue/logo_64x64_white.png
  projects/typescript-vue/package.json
  projects/typescript-vue/src/app.vue
  projects/typescript-vue/src/bpmn-utils.ts
  projects/typescript-vue/src/index.ts
  projects/typescript-vue/src/pizza-collaboration.bpmn
  projects/typescript-vue/src/shims-vue.d.ts
  projects/typescript-vue/src/style.css
  projects/typescript-vue/src/vite-env.d.ts
  projects/typescript-vue/tsconfig.json
  projects/typescript-vue/vite.config.js
Labels: enhancement

#503 ci: rename the artifact produced by the "check projects" workflow
  .github/workflows/check-projects.yml
Labels: chore

#504 fix: configure custom default fonts and colors
  examples/custom-bpmn-theme/custom-colors/README.md
  examples/custom-bpmn-theme/custom-colors/index.js
  examples/custom-bpmn-theme/custom-fonts/README.md
  examples/custom-bpmn-theme/custom-fonts/index.js
Labels: bug

#505 refactor: simplify reset of StyleDefault
  examples/custom-bpmn-theme/custom-colors/index.html
  examples/custom-bpmn-theme/custom-colors/index.js
  examples/custom-bpmn-theme/custom-fonts/index.html
  examples/custom-bpmn-theme/custom-fonts/index.js
  examples/overlays/custom-overlay-default-style/index.html
  examples/overlays/custom-overlay-default-style/index.js
  examples/static/js/style-defaults.js
Labels: refactoring

#512 refactor: move bpmn pizza diagram with other bpmn diagrams
  demo/predictions/index.html
  examples/static/js/diagram/bpmn-diagram-bpmn-spec-pizza.js
Labels: refactoring

#510 feat: reference the "bonita day 2023" demo in the home page
  README.md
  examples/index.html
  examples/static/img/preview/demo/bonita-day-2023.png
Labels: enhancement

#513 refactor: extract the data for the prediction demo in dedicated classes
  demo/predictions/index.html
  demo/predictions/js/data.js
  demo/predictions/js/prediction-use-case.js
Labels: refactoring

#514 refactor: extract the styling for the prediction demo in dedicated classes
  demo/predictions/index.html
  demo/predictions/js/data.js
  demo/predictions/js/prediction-use-case.js
  demo/predictions/js/style.js
Labels: depends on another PR :warning:, refactoring
